name: Nitter (Privacydevel)

on:
  push:
    paths:
      - ".github/workflows/nitter-privacydevel.yaml"

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 2,8,14,20 * * *"
  workflow_dispatch:

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-nitter:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone PrivacyDevel nitter
        run: |
          git clone --depth=1 https://github.com/PrivacyDevel/nitter.git nitter-privacydevel

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "./nitter-privacydevel"
          platforms: linux/amd64,linux/arm64/v8
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/ohaiibuzzle/nitter-privacydevel:latest