name: Nitter (Guest Account Branch)

on:
  push:
    paths:
      - ".github/workflows/nitter-guestaccounts.yaml"

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-nitter-amd64:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    strategy:
        matrix:
          arch: [arm64, amd64]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone PrivacyDevel nitter
        run: |
          git clone --depth=1 -b guest_accounts https://github.com/zedeus/nitter.git nitter-guestaccounts

      - if: matrix.arch == 'amd64'
        name: Build and push Docker image (amd64)
        uses: docker/build-push-action@v5
        with:
          context: "./nitter-guestaccounts"
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/ohaiibuzzle/nitter-guestaccounts:latest

      - if: matrix.arch == 'arm64'
        name: Build and push Docker image (arm64)
        uses: docker/build-push-action@v5
        with:
          context: "./nitter-guestaccounts"
          platforms: linux/arm64/v8
          file: './nitter-guestaccounts/Dockerfile.arm64'
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/ohaiibuzzle/nitter-guestaccounts:latest-arm64
